### ISSUE TITLE
Default chat is in legacy model

### ISSUE THREAD

**Issue by qiangweihewu** [RainEggplant/chatgpt-telegram-bot#16]
Hi there! Thank you for this project!
I just found the chat is in legacy model, not in default model in  browser type. Is it possible to make the chat in default model? 
Also, does it support multiple chats in different chat_ids?
Thanks!

**Comment by RainEggplant** [comment]
> I just found the chat is in legacy model, not in default model in browser type.

What did you mean? I would assume you are using the official API. But unfortunately, the ChatGPT model (`text-davinci-002-render-sha`) is not accessible via the official API, so we have to use the `text-davinci-003` model to mimic the ChatGPT.

> Also, does it support multiple chats in different chat_ids?

This is a planned feature. See this [comment in #15](https://github.com/RainEggplant/chatgpt-telegram-bot/issues/15#issuecomment-1438559763).

**Comment by NightCorpse** [comment]
its using the legacy model in the browser option, i want to use the default
