### ISSUE TITLE
auto delete conversation thread after /reset

### ISSUE THREAD

**Issue by soyelmismo** [RainEggplant/chatgpt-telegram-bot#28]
... or delete all the conversations.
from chatgpt api.

maybe this can be useful:
https://github.com/wong2/chatgpt-google-extension/blob/7c52dc9b43b905b7a9ef82953eecc49dd5a3f247/src/background/providers/chatgpt.ts#L76

it deletes the conversation when the search tab is closed.

**Comment by RainEggplant** [comment]
I think this only applies to the `unofficial` and `browser` API. However, the upstream API does not support this function. So you may need to request the feature in the API repo first.
