### ISSUE TITLE
 ChatGPT API error: SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by pawangspandey** [RainEggplant/chatgpt-telegram-bot#3]
I am getting this error while asking to write any code

**Comment by pawangspandey** [comment]
@VolanDeVovan @RainEggplant  We need to update the chatgpt package to `3.3.12 `
This will solve the issue

**Comment by RainEggplant** [comment]
Thank you for pointing this out. I will update it right now.
