### ISSUE TITLE
all of Messages from telegram will Join the queue，but it' will never get handled

### ISSUE THREAD

**Issue by kintong3000** [RainEggplant/chatgpt-telegram-bot#35]
Sometimes the program running will get an error,but program still run.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/85821314/223760678-e72ef0b8-27cf-41bc-870f-0d81eb68b8ec.png">
then,all of Messages from telegram will Join the queue，and it' will never get handled unless Restart the program.

version 2.3.1

**Comment by RainEggplant** [comment]
I've added a timeout mechanism in #36 as an initial fix. May add a retry mechanism later.

**Comment by kintong3000** [comment]
Thank you so much for your help!  I really appreciate you taking the time to update it.

**Comment by kintong3000** [comment]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/85821314/224461342-11dcbf47-03c6-441d-b76e-88051b25f8a7.png">
Do you have any way to improve🤔

**Comment by RainEggplant** [comment]
> <img alt="image" width="1104" src="https://user-images.githubusercontent.com/85821314/224461342-11dcbf47-03c6-441d-b76e-88051b25f8a7.png">
> Do you have any way to improve🤔

Probably related to #34.
