### ISSUE TITLE
chatgpt-v3 npm package missing

### ISSUE THREAD

**Issue by nonoo** [RainEggplant/chatgpt-telegram-bot#37]
The pnpm build command fails when using v2.4.0. Log indicates that chatgpt-v3 npm package is missing. I can't install it with npm and can't find it anywhere on the internet.

I've managed to successfully build the bot by removing all chatgpt-v3 references from the src directory, but I think it's not the most ideal solution :)

Where can I get the chatgpt-v3 npm package, or what's the recommended method to build the bot with it?

**Comment by RainEggplant** [comment]
The `chatgpt-v3` is an alias for the `chatgpt` package at version `3.5.1`, which is specified in the `package.json`. So, have you tried running `pnpm i` first to install the packages and then `pnpm build`?

**Comment by nonoo** [comment]
Yes. I've ran `pnpm install` which completed without issues, then `pnpm build`, which gave errors that it can't find chatgpt-v3. This is under the latest stable Debian, with npm 9.6.0 and pnpm 7.28.0

**Comment by RainEggplant** [comment]
That's pretty weird. I have no problems building on Windows 10 and Ubuntu 22.04 (both pnpm 7.19.0), and the [docker build action](https://github.com/RainEggplant/chatgpt-telegram-bot/actions/runs/4382032943/jobs/7670675329) is also running fine.

**Comment by RainEggplant** [comment]
@nonoo That's probably because I moved `chatgpt-v3` to optional dependencies. Run `pnpm install --force` and it will be fine.

**Comment by hoxnox** [comment]
docker images doesn't start because of the same error

**Comment by nonoo** [comment]
`pnpm install --force` fixed the issue, thanks!
