### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by suikaremilia** [RainEggplant/chatgpt-telegram-bot#4]
I got this error when I start it up

```
:~/chatgpt-telegram-bot$ xvfb-run -a --server-args="-screen 0 1280x800x24 -nolisten tcp -dpi 96 +extension RANDR" pnpm start

> chatgpt-telegram-bot@1.0.3 start /home/chatgpt-telegram-bot
> node dist/index.js

TimeoutError: Waiting for selector `#password` failed: Waiting failed: 180000ms exceeded
    at Timeout.<anonymous> (/home/chatgpt-telegram-bot/node_modules/.pnpm/registry.npmmirror.com+puppeteer-core@19.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
 ELIFECYCLE  Command failed with exit code 1.
```

It looks like there is no password, but I am logged in through Google authentication and I'm sure I set the correct password in .env.
I checked, there are no special characters in my password.
So can give some help?THX

**Comment by RainEggplant** [comment]
Have you set `IS_GOOGLE_LOGIN` to `true` in `.env`? If not, the bot will use OpenAI authentication, which requires you to solve the recaptcha before you can input the password (like https://github.com/transitive-bullshit/chatgpt-api/issues/199).

If this problem exists when `IS_GOOGLE_LOGIN=true`, you may forward the display to your local computer and see what went wrong during the authentication.

**Comment by RainEggplant** [comment]
> IS_GOOGLE_LOGIN=ture

It's `true` not `ture` 😂.
