### ISSUE TITLE
[Error]: 404: Not Found

### ISSUE THREAD

**Issue by DukeJerry** [RainEggplant/chatgpt-telegram-bot#40]
### Not a duplicate issue

- [X] I have searched the existing issues and confirmed this issue is not a duplicate.

### Verify ChatGPT service is operational

- [X] I have checked [status.openai.com](https://status.openai.com) and ChatGPT is operational.

### Bot version

v.2.4.0

### API type

official

### Environment details

Node.js version: 18
operating system: Debian 11 x64 (bullseye)

### Describe the Bug

I followed the instructions
run the command "pnpm build && pnpm start" return the error

loadFromJsonFile ok
3/20/2023, 3:39:13 AM 🔮 ChatGPT API has started...
bot.launch
ChatGptTelegraf:InChat :  undefined
start ServerApp
404: Not Found
Error: 404: Not Found
    at Telegram.callApi (/root/chatgpt-telegram-bot_RainEggplant/node_modules/.pnpm/telegraf@4.12.2/node_modules/telegraf/lib/core/network/client.js:293:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegraf.launch (/root/chatgpt-telegram-bot_RainEggplant/node_modules/.pnpm/telegraf@4.12.2/node_modules/telegraf/lib/telegraf.js:182:78)

**Comment by RainEggplant** [comment]
Did you modify the code? This project uses `node-telegram-bot-api` instead of `telegraf`. However, the error message seems to be related to `telegraf`.

**Comment by DukeJerry** [comment]
> Did you modify the code? This project uses `node-telegram-bot-api` instead of `telegraf`. However, the error message seems to be related to `telegraf`.

I did not modify any code， just use“git clone”，and use the command to install、build and start.

**Comment by RainEggplant** [comment]
Please double-check that your codebase matches this project and your package installation is correct. This project should not be raising any error related to `telegraf`.

**Comment by DukeJerry** [comment]
> Please double-check that your codebase matches this project and your package installation is correct. This project should not be raising any error related to `telegraf`.

I found the code udner BotBase.ts "import {Telegraf, session, Context} from 'telegraf';"

**Comment by RainEggplant** [comment]
> I found the code udner BotBase.ts "import {Telegraf, session, Context} from 'telegraf';"

That's not my code. Please reclone this repository.

**Comment by DukeJerry** [comment]
OK, I cleanup the dir ,reclone the repository。
rebuild it
All is fine，Thanks a lot
