### ISSUE TITLE
Telegram bot doesn't autofill bot name when command is issued without space in group chats

### ISSUE THREAD

**Issue by chrishkirk** [RainEggplant/chatgpt-telegram-bot#41]
### Not a duplicate issue

- [X] I have searched the existing issues and confirmed this issue is not a duplicate.

### Verify ChatGPT service is operational

- [X] I have checked [status.openai.com](https://status.openai.com) and ChatGPT is operational.

### Bot version

Latest

### API type

official

### Environment details

Docker

### Describe the Bug

When issuing a command to the ChatGPT Telegram bot in a group chat, it currently accepts the format "/chat@bot-name". However, if there isn't a space between the command (/chat) and the bot name, Telegram doesn't autofill the bot name, which would be super helpful.

This issue appears to be specific to Telegram group chats.

It would be helpful if the bot could handle commands issued with a space between the command and the bot name in group chats, so that users can enter commands more easily and intuitively.

Thank you for your attention to this matter.

**Comment by RainEggplant** [comment]
Hi! If I understand correctly, are you suggesting that the bot should be able to handle commands like `/reset @bot_name` in group chats?

As for autofilling, it is handled by the Telegram client and cannot be controlled by the bot. It seems that different clients have different implementations (Telegram Desktop can autofill the bot name in group chats, but Telegram Android cannot.)

And just in case, you only need to prepend your message with `/chat` in group chats. `@bot_name` is only required for commands (such as `/reset@bot_name`).
