### ISSUE TITLE
[Feature Request]: Does the Official API Support GPT-4?

### ISSUE THREAD

**Issue by chk86** [RainEggplant/chatgpt-telegram-bot#45]
### Not a duplicate feature request

- [X] I have searched the existing issues and confirmed this feature request is not a duplicate.

### Supported by the upstream API

- [x] This feature can be implemented using the upstream API.

### Describe the feature

Can the default model be switched at all? I saw that the unofficial type you can specify the chatgpt model, but I wasn't sure if that was the same for the official type. I went ahead and specified "gpt-4" in the local.json file, but unsure if it's working or not.

**Comment by RainEggplant** [comment]
Yes. You just need to specify the correct model name for GPT-4 in `api.official.completionParams.model`.

**Comment by chk86** [comment]
Just to be clear, where do you specify the correct model? I attempted changing the model in the local.json file, but that does not appear to do anything. It still uses the 3.5-turbo model.

**Comment by RainEggplant** [comment]
> Just to be clear, where do you specify the correct model? I attempted changing the model in the local.json file, but that does not appear to do anything. It still uses the 3.5-turbo model.

Did you set `api.official.completionParams.model` to `gpt-4` in `local.json` like this?

```json
{
  "api": {
    "official": {
      "completionParams": {
        "model": "gpt-4"
      },
      "maxModelTokens": 8100
    }
}
```

 According to the author (https://github.com/transitive-bullshit/chatgpt-api/issues/471#issuecomment-1469260101) of the chatgpt node api, GPT-4 is supported.

**Comment by chk86** [comment]
@RainEggplant No! Thanks for taking the time to show me. I had model outside of the completionParms braces. Now it's working fine. Thanks!
