### ISSUE TITLE
Browser option using GPT3.5 Legacy instead of GPT3.5 Default

### ISSUE THREAD

**Issue by NightCorpse** [RainEggplant/chatgpt-telegram-bot#50]
Unfortunately this issue affects the speed at which the bot generates responses.

(Note: the unofficial is not working for me, I am dependent on the browser option)

**Comment by Vadko** [comment]
Unfortunately, browser API is no longer supported on chatgpt-api library. From what I've seen in docs it is not possible to choose model for browser-api.
