### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by VectorZhao** [RainEggplant/chatgpt-telegram-bot#6]
2/3/2023, 3:23:37 PM 📩 Message from @xxxx in private chat:
hello
2/3/2023, 3:23:37 PM ⛔️ ChatGPT API error: ChatGPTAPI error 400
ChatGPT "xxxxxx" error 400; An error ocurred. Try refreshing your browser.
 

how to solve it？

**Comment by RainEggplant** [comment]
It seems that OpenAI has changed the model from `text-davinci-002-render-next` back to `text-davinci-002-render`, causing a mismatch with the API `chatgpt@3.5.2` (note that we are currently sticking with v3 before v4 becomes stable):

https://github.com/transitive-bullshit/chatgpt-api/commit/b8f03f3c1163277119e9ba386f809561a1e17da3

To solve this, you need to downgrade `chatgpt` from 3.5.2 to 3.5.1. I will also update the `package.json`.
